import type { Permission } from "@/lib/auth/permissions";
import { PERMISSIONS } from "@/lib/auth/permissions";

/** Floor/orders can read menu & tables without admin manage keys. */
export const TILL_READ_MENU: Permission[] = [
  PERMISSIONS.TICKETS_OPEN,
  PERMISSIONS.MENU_MANAGE,
  PERMISSIONS.MENU_SOLD_OUT,
];

export const TILL_READ_TABLES: Permission[] = [
  PERMISSIONS.TICKETS_OPEN,
  PERMISSIONS.TABLES_MANAGE,
];

export const TILL_READ_TICKETS: Permission[] = [
  PERMISSIONS.TICKETS_OPEN,
  PERMISSIONS.TICKETS_LINES,
  PERMISSIONS.TICKETS_FIRE,
];

export const TILL_READ_SOLD_OUT: Permission[] = [
  PERMISSIONS.TICKETS_OPEN,
  PERMISSIONS.MENU_SOLD_OUT,
];

export const TILL_READ_DAILY_MENU: Permission[] = [
  PERMISSIONS.TICKETS_OPEN,
  PERMISSIONS.ADMIN_DAILY_MENU,
  PERMISSIONS.MENU_MANAGE,
];

export const HOTEL_READ_IN_HOUSE: Permission[] = [
  PERMISSIONS.ROOM_CHARGE,
  PERMISSIONS.PMS_ENTITLEMENTS,
  PERMISSIONS.DEFER_HUB,
];

export const HOTEL_READ_RESERVATIONS: Permission[] = [
  PERMISSIONS.RESERVATIONS_OPEN_TICKET,
  PERMISSIONS.SCREEN_CALENDAR,
];

export const HOTEL_READ_BANQUETS: Permission[] = [
  PERMISSIONS.RESERVATIONS_OPEN_TICKET,
  PERMISSIONS.ROOM_SERVICE,
  PERMISSIONS.TICKETS_OPEN,
];

export const OUTLET_LIST_READ: Permission[] = [
  PERMISSIONS.TICKETS_OPEN,
  PERMISSIONS.OUTLETS_MANAGE,
  PERMISSIONS.OUTLET_BIND,
];

export const DELIVERY_ACCEPT: Permission[] = [
  PERMISSIONS.TICKETS_OPEN,
  PERMISSIONS.TICKETS_PAY,
  PERMISSIONS.MENU_MANAGE,
];

export const ROSTER_WRITE: Permission[] = [
  PERMISSIONS.STAFF_PIN,
  PERMISSIONS.LABOR_ROSTER_WRITE,
];
