-- SHARED-schema: additive organizationId on tenant roots
CREATE TABLE IF NOT EXISTS "_era_organization_bind" (
  id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  "organizationId" TEXT NOT NULL,
  "boundAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "boundBy" TEXT
);
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Tenant" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "Tenant_code_key";
DROP INDEX IF EXISTS "Tenant_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "Tenant_organization_id_code_key" ON "Tenant"("organization_id", "code");
CREATE INDEX IF NOT EXISTS "Tenant_organization_id_idx" ON "Tenant"("organization_id");
ALTER TABLE "Outlet" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Outlet" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "Outlet_organization_id_idx" ON "Outlet"("organization_id");
ALTER TABLE "PatientRef" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "PatientRef" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "PatientRef_refCode_key";
DROP INDEX IF EXISTS "PatientRef_refCode_key";
CREATE UNIQUE INDEX IF NOT EXISTS "PatientRef_organization_id_refCode_key" ON "PatientRef"("organization_id", "refCode");
CREATE INDEX IF NOT EXISTS "PatientRef_organization_id_idx" ON "PatientRef"("organization_id");
ALTER TABLE "Practitioner" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Practitioner" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "Practitioner_code_key";
DROP INDEX IF EXISTS "Practitioner_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "Practitioner_organization_id_code_key" ON "Practitioner"("organization_id", "code");
CREATE INDEX IF NOT EXISTS "Practitioner_organization_id_idx" ON "Practitioner"("organization_id");
ALTER TABLE "Room" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Room" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "Room_code_key";
DROP INDEX IF EXISTS "Room_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "Room_organization_id_code_key" ON "Room"("organization_id", "code");
CREATE INDEX IF NOT EXISTS "Room_organization_id_idx" ON "Room"("organization_id");
ALTER TABLE "Resource" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Resource" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "Resource_code_key";
DROP INDEX IF EXISTS "Resource_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "Resource_organization_id_code_key" ON "Resource"("organization_id", "code");
CREATE INDEX IF NOT EXISTS "Resource_organization_id_idx" ON "Resource"("organization_id");
ALTER TABLE "ResourceBooking" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ResourceBooking" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "ResourceBooking_organization_id_idx" ON "ResourceBooking"("organization_id");
ALTER TABLE "Appointment" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Appointment" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "Appointment_organization_id_idx" ON "Appointment"("organization_id");
ALTER TABLE "Visit" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Visit" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "Visit_organization_id_idx" ON "Visit"("organization_id");
ALTER TABLE "LabOrder" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "LabOrder" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "LabOrder_organization_id_idx" ON "LabOrder"("organization_id");
ALTER TABLE "Modality" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Modality" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "Modality_code_key";
DROP INDEX IF EXISTS "Modality_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "Modality_organization_id_code_key" ON "Modality"("organization_id", "code");
CREATE INDEX IF NOT EXISTS "Modality_organization_id_idx" ON "Modality"("organization_id");
ALTER TABLE "DiagnosticService" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "DiagnosticService" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "DiagnosticService_code_key";
DROP INDEX IF EXISTS "DiagnosticService_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "DiagnosticService_organization_id_code_key" ON "DiagnosticService"("organization_id", "code");
CREATE INDEX IF NOT EXISTS "DiagnosticService_organization_id_idx" ON "DiagnosticService"("organization_id");
ALTER TABLE "ImagingPhrase" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ImagingPhrase" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "ImagingPhrase_code_key";
DROP INDEX IF EXISTS "ImagingPhrase_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "ImagingPhrase_organization_id_code_key" ON "ImagingPhrase"("organization_id", "code");
CREATE INDEX IF NOT EXISTS "ImagingPhrase_organization_id_idx" ON "ImagingPhrase"("organization_id");
ALTER TABLE "ClinicLookup" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ClinicLookup" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "ClinicLookup_kind_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "ClinicLookup_organization_id_kind_code_key" ON "ClinicLookup"("organization_id", "kind", "code");
CREATE INDEX IF NOT EXISTS "ClinicLookup_organization_id_idx" ON "ClinicLookup"("organization_id");
ALTER TABLE "ProcedureCompatibilityRule" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ProcedureCompatibilityRule" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "ProcedureCompatibilityRule_organization_id_idx" ON "ProcedureCompatibilityRule"("organization_id");
ALTER TABLE "ProcedureType" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ProcedureType" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "ProcedureType_code_key";
DROP INDEX IF EXISTS "ProcedureType_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "ProcedureType_organization_id_code_key" ON "ProcedureType"("organization_id", "code");
CREATE INDEX IF NOT EXISTS "ProcedureType_organization_id_idx" ON "ProcedureType"("organization_id");
ALTER TABLE "ProcedureRotationRule" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ProcedureRotationRule" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "ProcedureRotationRule_code_key";
DROP INDEX IF EXISTS "ProcedureRotationRule_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "ProcedureRotationRule_organization_id_code_key" ON "ProcedureRotationRule"("organization_id", "code");
CREATE INDEX IF NOT EXISTS "ProcedureRotationRule_organization_id_idx" ON "ProcedureRotationRule"("organization_id");
ALTER TABLE "ProcedureSubstitutionRule" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ProcedureSubstitutionRule" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "ProcedureSubstitutionRule_organization_id_idx" ON "ProcedureSubstitutionRule"("organization_id");
ALTER TABLE "ProcedureRule" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ProcedureRule" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "ProcedureRule_organization_id_idx" ON "ProcedureRule"("organization_id");
ALTER TABLE "PatientContraindication" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "PatientContraindication" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "PatientContraindication_organization_id_idx" ON "PatientContraindication"("organization_id");
ALTER TABLE "ServiceCatalogCache" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ServiceCatalogCache" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "ServiceCatalogCache_code_key";
DROP INDEX IF EXISTS "ServiceCatalogCache_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "ServiceCatalogCache_organization_id_code_key" ON "ServiceCatalogCache"("organization_id", "code");
CREATE INDEX IF NOT EXISTS "ServiceCatalogCache_organization_id_idx" ON "ServiceCatalogCache"("organization_id");
ALTER TABLE "VisitDiscountAudit" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "VisitDiscountAudit" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "VisitDiscountAudit_organization_id_idx" ON "VisitDiscountAudit"("organization_id");
ALTER TABLE "ClinicalTemplate" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ClinicalTemplate" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "ClinicalTemplate_code_key";
DROP INDEX IF EXISTS "ClinicalTemplate_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "ClinicalTemplate_organization_id_code_key" ON "ClinicalTemplate"("organization_id", "code");
CREATE INDEX IF NOT EXISTS "ClinicalTemplate_organization_id_idx" ON "ClinicalTemplate"("organization_id");
ALTER TABLE "ProgramTemplate" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ProgramTemplate" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "ProgramTemplate_code_key";
DROP INDEX IF EXISTS "ProgramTemplate_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "ProgramTemplate_organization_id_code_key" ON "ProgramTemplate"("organization_id", "code");
CREATE INDEX IF NOT EXISTS "ProgramTemplate_organization_id_idx" ON "ProgramTemplate"("organization_id");
ALTER TABLE "ProgramInstance" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ProgramInstance" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "ProgramInstance_organization_id_idx" ON "ProgramInstance"("organization_id");
ALTER TABLE "ProcedureOrder" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ProcedureOrder" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "ProcedureOrder_organization_id_idx" ON "ProcedureOrder"("organization_id");
ALTER TABLE "InpatientAdmission" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "InpatientAdmission" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "InpatientAdmission_organization_id_idx" ON "InpatientAdmission"("organization_id");
ALTER TABLE "Ward" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Ward" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "Ward_code_key";
DROP INDEX IF EXISTS "Ward_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "Ward_organization_id_code_key" ON "Ward"("organization_id", "code");
CREATE INDEX IF NOT EXISTS "Ward_organization_id_idx" ON "Ward"("organization_id");
ALTER TABLE "Bed" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Bed" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "Bed_organization_id_idx" ON "Bed"("organization_id");
ALTER TABLE "BedAssignment" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "BedAssignment" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "BedAssignment_organization_id_idx" ON "BedAssignment"("organization_id");
ALTER TABLE "CpoeEntry" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "CpoeEntry" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "CpoeEntry_organization_id_idx" ON "CpoeEntry"("organization_id");
ALTER TABLE "ClinicShift" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ClinicShift" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "ClinicShift_code_key";
DROP INDEX IF EXISTS "ClinicShift_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "ClinicShift_organization_id_code_key" ON "ClinicShift"("organization_id", "code");
CREATE INDEX IF NOT EXISTS "ClinicShift_organization_id_idx" ON "ClinicShift"("organization_id");
ALTER TABLE "ClinicReceipt" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ClinicReceipt" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "ClinicReceipt_organization_id_idx" ON "ClinicReceipt"("organization_id");
ALTER TABLE "ProcedureChargeLog" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ProcedureChargeLog" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "ProcedureChargeLog_organization_id_idx" ON "ProcedureChargeLog"("organization_id");
ALTER TABLE "ProcessedEvent" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ProcessedEvent" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "ProcessedEvent_correlationId_key";
DROP INDEX IF EXISTS "ProcessedEvent_correlationId_key";
CREATE UNIQUE INDEX IF NOT EXISTS "ProcessedEvent_organization_id_correlationId_key" ON "ProcessedEvent"("organization_id", "correlationId");
CREATE INDEX IF NOT EXISTS "ProcessedEvent_organization_id_idx" ON "ProcessedEvent"("organization_id");
ALTER TABLE "Role" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Role" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "Role_code_key";
DROP INDEX IF EXISTS "Role_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "Role_organization_id_code_key" ON "Role"("organization_id", "code");
CREATE INDEX IF NOT EXISTS "Role_organization_id_idx" ON "Role"("organization_id");
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "User" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "User_login_key";
DROP INDEX IF EXISTS "User_login_key";
CREATE UNIQUE INDEX IF NOT EXISTS "User_organization_id_login_key" ON "User"("organization_id", "login");
CREATE INDEX IF NOT EXISTS "User_organization_id_idx" ON "User"("organization_id");
ALTER TABLE "satellite_audit_logs" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "satellite_audit_logs" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "satellite_audit_logs_organization_id_idx" ON "satellite_audit_logs"("organization_id");
ALTER TABLE "QueueTicket" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "QueueTicket" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
CREATE INDEX IF NOT EXISTS "QueueTicket_organization_id_idx" ON "QueueTicket"("organization_id");
ALTER TABLE "LisFileProfile" ADD COLUMN IF NOT EXISTS "organization_id" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "LisFileProfile" t SET "organization_id" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organization_id") WHERE t."organization_id" = 'unbound';
DROP INDEX IF EXISTS "LisFileProfile_name_key";
DROP INDEX IF EXISTS "LisFileProfile_name_key";
CREATE UNIQUE INDEX IF NOT EXISTS "LisFileProfile_organization_id_name_key" ON "LisFileProfile"("organization_id", "name");
CREATE INDEX IF NOT EXISTS "LisFileProfile_organization_id_idx" ON "LisFileProfile"("organization_id");
