ALTER TABLE "PatientRef" ADD COLUMN IF NOT EXISTS "nationality" TEXT DEFAULT 'AZ';
ALTER TABLE "PatientRef" ADD COLUMN IF NOT EXISTS "finCode" TEXT;
ALTER TABLE "PatientRef" ADD COLUMN IF NOT EXISTS "passportNumber" TEXT;
ALTER TABLE "PatientRef" ADD COLUMN IF NOT EXISTS "issuingCountry" TEXT;
