/**
 * DESIGN.md — ERA ecosystem UI tokens (umbrella: ../../DESIGN.md).
 * Re-exports shared kit tokens; F&B POS adds no satellite-specific overrides.
 */
export {
  APP_SHELL_CLASS as SHELL_CLASS,
  CARD_CONTAINER_CLASS as CARD_CLASS,
  DATA_TABLE_CLASS,
  DATA_TABLE_HEAD_ROW_CLASS,
  DATA_TABLE_TD_CLASS,
  DATA_TABLE_TH_LEFT_CLASS,
  DATA_TABLE_TR_CLASS,
  DATA_TABLE_VIEWPORT_CLASS,
  DESIGN as COLORS,
  FORM_FIELD_GROUP_CLASS,
  FORM_STACK_CLASS,
  MODAL_DIALOG_CONTENT_CLASS,
  MODAL_FIELD_LABEL_CLASS,
  MODAL_FOOTER_ACTIONS_CLASS,
  MODAL_FOOTER_OUTLINE_CLASS,
  MODAL_FOOTER_PRIMARY_CLASS,
  MODAL_INPUT_CLASS as INPUT_CLASS,
  MODAL_INPUT_CLASS,
  PRIMARY_BUTTON_CLASS as PRIMARY_BTN_CLASS,
  PRIMARY_BUTTON_CLASS,
  SECONDARY_BUTTON_CLASS as SECONDARY_BTN_CLASS,
  SECONDARY_BUTTON_CLASS,
  TABLE_ROW_ICON_BTN_CLASS,
} from "@era/satellite-kit/ui";
