/**
 * Role → canonical CP keys for Finance DB RolePermission joins.
 * Not the AuthZ door (JWT from Orchestrator). Aligns with @era/contracts templates.
 */
export const ROLE_PERMISSION_MATRIX: Record<string, string[]> = {
  OWNER: [
    "api:billing.read",
    "api:billing.manage",
    "api:ledger.post",
    "api:ledger.read",
    "api:ledger.period_close",
    "api:invoices.create",
    "api:invoices.update",
    "api:purchases.manage",
    "api:payroll.hr_card",
    "api:payroll.money",
    "api:inventory.approve",
    "api:psa.manage",
    "api:reports.nas",
    "api:book.mgmt",
    "admin:org.settings",
  ],
  ADMIN: [
    "api:billing.read",
    "api:ledger.post",
    "api:ledger.read",
    "api:ledger.period_close",
    "api:invoices.create",
    "api:invoices.update",
    "api:purchases.manage",
    "api:payroll.hr_card",
    "api:payroll.money",
    "api:inventory.approve",
    "api:psa.manage",
    "api:reports.nas",
    "api:book.mgmt",
    "admin:org.settings",
  ],
  ACCOUNTANT: [
    "api:ledger.post",
    "api:ledger.read",
    "api:invoices.create",
    "api:invoices.update",
    "api:payroll.money",
    "api:reports.nas",
  ],
  USER: ["api:invoices.create", "api:reports.nas"],
  PROCUREMENT: ["api:purchases.manage", "api:reports.nas"],
  AUDITOR: ["api:ledger.read", "api:reports.nas"],
  WAREHOUSE_KEEPER: ["api:inventory.approve", "api:reports.nas"],
  HR_OFFICER: ["api:payroll.hr_card", "api:reports.nas"],
  HR_MANAGER: ["api:payroll.hr_card", "api:reports.nas"],
  DEPARTMENT_HEAD: ["api:invoices.create", "api:reports.nas"],
  DIRECTOR: [
    "api:billing.read",
    "api:billing.manage",
    "api:ledger.post",
    "api:ledger.read",
    "api:reports.nas",
    "api:book.mgmt",
  ],
  SUPER_ADMIN: [
    "api:billing.read",
    "api:billing.manage",
    "api:ledger.post",
    "api:ledger.read",
    "api:ledger.period_close",
    "api:invoices.create",
    "api:invoices.update",
    "api:purchases.manage",
    "api:payroll.hr_card",
    "api:payroll.money",
    "api:inventory.approve",
    "api:psa.manage",
    "api:reports.nas",
    "api:book.mgmt",
    "admin:org.settings",
    "admin:platform",
  ],
};
