import { z } from 'zod';

/** Shared PATCH body schema for reservation full card (also validated in API route). */
export const reservationFullPatchSchema = z.object({
  roomTypeId: z.string().uuid().optional(),
  ratePlanId: z.string().uuid().optional(),
  mealPlanId: z.string().uuid().nullable().optional(),
  agencyId: z.string().uuid().nullable().optional(),
  salesContractId: z.string().uuid().nullable().optional(),
  sourceId: z.string().uuid().nullable().optional(),
  roomId: z.string().uuid().nullable().optional(),
  guestId: z.string().uuid().optional(),
  checkInDate: z.coerce.date().optional(),
  checkOutDate: z.coerce.date().optional(),
  paymentMethod: z.enum(['CASH', 'CARD', 'COMPANY_ACCOUNT']).optional(),
  voucherNo: z.string().nullable().optional(),
  partyBillingMode: z.enum(['PRIMARY', 'EQUAL']).optional(),
  roomCount: z.number().int().min(1).optional(),
  adults: z.number().int().min(0).optional(),
  children11_6: z.number().int().min(0).optional(),
  children5_2: z.number().int().min(0).optional(),
  children1_0: z.number().int().min(0).optional(),
  market: z.string().nullable().optional(),
  segment: z.string().nullable().optional(),
  rateType: z.string().nullable().optional(),
  booker: z.string().nullable().optional(),
  guestRep: z.string().nullable().optional(),
  paidBy: z.string().nullable().optional(),
  vipType: z.string().nullable().optional(),
  accomType: z.string().nullable().optional(),
  recordType: z.string().nullable().optional(),
  specialStates: z.string().nullable().optional(),
  tripReason: z.string().nullable().optional(),
  resGroup: z.string().nullable().optional(),
  colorCode: z.string().nullable().optional(),
  resNo: z.string().nullable().optional(),
  shareNo: z.string().nullable().optional(),
  shareEligible: z.boolean().optional(),
  optionDate: z.coerce.date().nullable().optional(),
  optionState: z.string().nullable().optional(),
  salesProject: z.string().nullable().optional(),
  useManualRate: z.boolean().optional(),
  manualDailyRate: z.number().nullable().optional(),
  discountActive: z.boolean().optional(),
  creditLimitAzn: z.number().nonnegative().nullable().optional(),
  isLocked: z.boolean().optional(),
  preferredLocation: z.string().nullable().optional(),
  preferredBed: z.string().nullable().optional(),
  givenRoomTypeId: z.string().uuid().nullable().optional(),
  contractRef: z.string().nullable().optional(),
  notes: z.record(z.string(), z.string()).optional(),
  paxGuests: z
    .array(
      z.object({
        id: z.string().uuid().optional(),
        guestId: z.string().uuid().nullable().optional(),
        title: z.string().nullable().optional(),
        gender: z.string().nullable().optional(),
        firstName: z.string().nullable().optional(),
        lastName: z.string().nullable().optional(),
        nationality: z.string().nullable().optional(),
        birthDate: z.string().nullable().optional(),
        age: z.number().nullable().optional(),
        idCardNo: z.string().nullable().optional(),
        passportNo: z.string().nullable().optional(),
        memberNo: z.string().nullable().optional(),
        payStatus: z.string().nullable().optional(),
        externalResId: z.string().nullable().optional(),
        guestState: z.string().nullable().optional(),
        isPrimary: z.boolean().optional(),
        ownsFolio: z.boolean().optional(),
      }),
    )
    .optional(),
  dailyRates: z
    .array(
      z.object({
        stayDate: z.string(),
        amount: z.number(),
        manualFlag: z.boolean().optional(),
        currencyCode: z.string().optional(),
        fixPrice: z.boolean().optional(),
        discountPct: z.number().nullable().optional(),
      }),
    )
    .optional(),
});
