ALTER TABLE "HotelLookup" ADD COLUMN IF NOT EXISTS "nameAz" TEXT;
ALTER TABLE "HotelLookup" ADD COLUMN IF NOT EXISTS "nameRu" TEXT;
ALTER TABLE "HotelLookup" ADD COLUMN IF NOT EXISTS "nameEn" TEXT;

ALTER TABLE "RoomView" ADD COLUMN IF NOT EXISTS "nameAz" TEXT;
ALTER TABLE "RoomView" ADD COLUMN IF NOT EXISTS "nameRu" TEXT;
ALTER TABLE "RoomView" ADD COLUMN IF NOT EXISTS "nameEn" TEXT;

ALTER TABLE "BedType" ADD COLUMN IF NOT EXISTS "nameAz" TEXT;
ALTER TABLE "BedType" ADD COLUMN IF NOT EXISTS "nameRu" TEXT;
ALTER TABLE "BedType" ADD COLUMN IF NOT EXISTS "nameEn" TEXT;

ALTER TABLE "RoomType" ADD COLUMN IF NOT EXISTS "nameAz" TEXT;
ALTER TABLE "RoomType" ADD COLUMN IF NOT EXISTS "nameRu" TEXT;
ALTER TABLE "RoomType" ADD COLUMN IF NOT EXISTS "nameEn" TEXT;

ALTER TABLE "RatePlan" ADD COLUMN IF NOT EXISTS "nameAz" TEXT;
ALTER TABLE "RatePlan" ADD COLUMN IF NOT EXISTS "nameRu" TEXT;
ALTER TABLE "RatePlan" ADD COLUMN IF NOT EXISTS "nameEn" TEXT;

ALTER TABLE "RevenueCode" ADD COLUMN IF NOT EXISTS "nameAz" TEXT;
ALTER TABLE "RevenueCode" ADD COLUMN IF NOT EXISTS "nameRu" TEXT;
ALTER TABLE "RevenueCode" ADD COLUMN IF NOT EXISTS "nameEn" TEXT;
