-- SHARED-schema: additive organizationId on tenant roots
CREATE TABLE IF NOT EXISTS "_era_organization_bind" (
  id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  "organizationId" TEXT NOT NULL,
  "boundAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "boundBy" TEXT
);
UPDATE "HotelProfile" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "HotelProfile_propertyCode_key";
DROP INDEX IF EXISTS "HotelProfile_propertyCode_key";
CREATE UNIQUE INDEX IF NOT EXISTS "HotelProfile_organizationId_propertyCode_key" ON "HotelProfile"("organizationId", "propertyCode");
CREATE INDEX IF NOT EXISTS "HotelProfile_organizationId_idx" ON "HotelProfile"("organizationId");
ALTER TABLE "Role" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Role" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "Role_code_key";
DROP INDEX IF EXISTS "Role_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "Role_organizationId_code_key" ON "Role"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "Role_organizationId_idx" ON "Role"("organizationId");
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "User" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "User_login_key";
DROP INDEX IF EXISTS "User_login_key";
CREATE UNIQUE INDEX IF NOT EXISTS "User_organizationId_login_key" ON "User"("organizationId", "login");
CREATE INDEX IF NOT EXISTS "User_organizationId_idx" ON "User"("organizationId");
ALTER TABLE "HotelLookup" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "HotelLookup" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "HotelLookup_kind_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "HotelLookup_organizationId_kind_code_key" ON "HotelLookup"("organizationId", "kind", "code");
CREATE INDEX IF NOT EXISTS "HotelLookup_organizationId_idx" ON "HotelLookup"("organizationId");
ALTER TABLE "RoomView" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "RoomView" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "RoomView_code_key";
DROP INDEX IF EXISTS "RoomView_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "RoomView_organizationId_code_key" ON "RoomView"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "RoomView_organizationId_idx" ON "RoomView"("organizationId");
ALTER TABLE "BedType" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "BedType" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "BedType_code_key";
DROP INDEX IF EXISTS "BedType_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "BedType_organizationId_code_key" ON "BedType"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "BedType_organizationId_idx" ON "BedType"("organizationId");
ALTER TABLE "RoomType" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "RoomType" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "RoomType_code_key";
DROP INDEX IF EXISTS "RoomType_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "RoomType_organizationId_code_key" ON "RoomType"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "RoomType_organizationId_idx" ON "RoomType"("organizationId");
ALTER TABLE "Room" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Room" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "Room_roomNumber_key";
DROP INDEX IF EXISTS "Room_roomNumber_key";
CREATE UNIQUE INDEX IF NOT EXISTS "Room_organizationId_roomNumber_key" ON "Room"("organizationId", "roomNumber");
CREATE INDEX IF NOT EXISTS "Room_organizationId_idx" ON "Room"("organizationId");
ALTER TABLE "MealPlan" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "MealPlan" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "MealPlan_code_key";
DROP INDEX IF EXISTS "MealPlan_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "MealPlan_organizationId_code_key" ON "MealPlan"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "MealPlan_organizationId_idx" ON "MealPlan"("organizationId");
ALTER TABLE "RatePlan" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "RatePlan" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "RatePlan_code_key";
DROP INDEX IF EXISTS "RatePlan_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "RatePlan_organizationId_code_key" ON "RatePlan"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "RatePlan_organizationId_idx" ON "RatePlan"("organizationId");
ALTER TABLE "AddOn" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "AddOn" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "AddOn_code_key";
DROP INDEX IF EXISTS "AddOn_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "AddOn_organizationId_code_key" ON "AddOn"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "AddOn_organizationId_idx" ON "AddOn"("organizationId");
ALTER TABLE "ProcedureService" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ProcedureService" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "ProcedureService_code_key";
DROP INDEX IF EXISTS "ProcedureService_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "ProcedureService_organizationId_code_key" ON "ProcedureService"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "ProcedureService_organizationId_idx" ON "ProcedureService"("organizationId");
ALTER TABLE "Department" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Department" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "Department_code_key";
DROP INDEX IF EXISTS "Department_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "Department_organizationId_code_key" ON "Department"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "Department_organizationId_idx" ON "Department"("organizationId");
ALTER TABLE "RevenueCode" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "RevenueCode" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "RevenueCode_code_key";
DROP INDEX IF EXISTS "RevenueCode_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "RevenueCode_organizationId_code_key" ON "RevenueCode"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "RevenueCode_organizationId_idx" ON "RevenueCode"("organizationId");
ALTER TABLE "BookingSource" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "BookingSource" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "BookingSource_code_key";
DROP INDEX IF EXISTS "BookingSource_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "BookingSource_organizationId_code_key" ON "BookingSource"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "BookingSource_organizationId_idx" ON "BookingSource"("organizationId");
ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Agency" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "Agency_code_key";
DROP INDEX IF EXISTS "Agency_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "Agency_organizationId_code_key" ON "Agency"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "Agency_organizationId_idx" ON "Agency"("organizationId");
ALTER TABLE "SalesContract" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "SalesContract" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "SalesContract_code_key";
DROP INDEX IF EXISTS "SalesContract_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "SalesContract_organizationId_code_key" ON "SalesContract"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "SalesContract_organizationId_idx" ON "SalesContract"("organizationId");
ALTER TABLE "ReservationGroup" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "ReservationGroup" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "ReservationGroup_code_key";
DROP INDEX IF EXISTS "ReservationGroup_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "ReservationGroup_organizationId_code_key" ON "ReservationGroup"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "ReservationGroup_organizationId_idx" ON "ReservationGroup"("organizationId");
ALTER TABLE "AllotmentBlock" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "AllotmentBlock" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "AllotmentBlock_code_key";
DROP INDEX IF EXISTS "AllotmentBlock_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "AllotmentBlock_organizationId_code_key" ON "AllotmentBlock"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "AllotmentBlock_organizationId_idx" ON "AllotmentBlock"("organizationId");
ALTER TABLE "Guest" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Guest" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
CREATE INDEX IF NOT EXISTS "Guest_organizationId_idx" ON "Guest"("organizationId");
ALTER TABLE "Reservation" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Reservation" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
CREATE INDEX IF NOT EXISTS "Reservation_organizationId_idx" ON "Reservation"("organizationId");
ALTER TABLE "Folio" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Folio" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
CREATE INDEX IF NOT EXISTS "Folio_organizationId_idx" ON "Folio"("organizationId");
ALTER TABLE "PromotionCode" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "PromotionCode" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "PromotionCode_code_key";
DROP INDEX IF EXISTS "PromotionCode_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "PromotionCode_organizationId_code_key" ON "PromotionCode"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "PromotionCode_organizationId_idx" ON "PromotionCode"("organizationId");
ALTER TABLE "Housekeeper" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Housekeeper" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "Housekeeper_code_key";
DROP INDEX IF EXISTS "Housekeeper_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "Housekeeper_organizationId_code_key" ON "Housekeeper"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "Housekeeper_organizationId_idx" ON "Housekeeper"("organizationId");
ALTER TABLE "MinibarItem" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "MinibarItem" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "MinibarItem_code_key";
DROP INDEX IF EXISTS "MinibarItem_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "MinibarItem_organizationId_code_key" ON "MinibarItem"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "MinibarItem_organizationId_idx" ON "MinibarItem"("organizationId");
ALTER TABLE "SpaPlace" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "SpaPlace" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "SpaPlace_code_key";
DROP INDEX IF EXISTS "SpaPlace_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "SpaPlace_organizationId_code_key" ON "SpaPlace"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "SpaPlace_organizationId_idx" ON "SpaPlace"("organizationId");
ALTER TABLE "Channel" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Channel" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "Channel_code_key";
DROP INDEX IF EXISTS "Channel_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "Channel_organizationId_code_key" ON "Channel"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "Channel_organizationId_idx" ON "Channel"("organizationId");
ALTER TABLE "Stay" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "Stay" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
CREATE INDEX IF NOT EXISTS "Stay_organizationId_idx" ON "Stay"("organizationId");
ALTER TABLE "CashShift" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "CashShift" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
CREATE INDEX IF NOT EXISTS "CashShift_organizationId_idx" ON "CashShift"("organizationId");
ALTER TABLE "BusinessDay" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "BusinessDay" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
CREATE INDEX IF NOT EXISTS "BusinessDay_organizationId_idx" ON "BusinessDay"("organizationId");
ALTER TABLE "NightAuditRun" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "NightAuditRun" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
CREATE INDEX IF NOT EXISTS "NightAuditRun_organizationId_idx" ON "NightAuditRun"("organizationId");
ALTER TABLE "HousekeepingTask" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "HousekeepingTask" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
CREATE INDEX IF NOT EXISTS "HousekeepingTask_organizationId_idx" ON "HousekeepingTask"("organizationId");
ALTER TABLE "PosResource" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "PosResource" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "PosResource_code_key";
DROP INDEX IF EXISTS "PosResource_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "PosResource_organizationId_code_key" ON "PosResource"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "PosResource_organizationId_idx" ON "PosResource"("organizationId");
ALTER TABLE "BanquetSaloon" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "BanquetSaloon" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
DROP INDEX IF EXISTS "BanquetSaloon_code_key";
DROP INDEX IF EXISTS "BanquetSaloon_code_key";
CREATE UNIQUE INDEX IF NOT EXISTS "BanquetSaloon_organizationId_code_key" ON "BanquetSaloon"("organizationId", "code");
CREATE INDEX IF NOT EXISTS "BanquetSaloon_organizationId_idx" ON "BanquetSaloon"("organizationId");
ALTER TABLE "BanquetMenuPackage" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "BanquetMenuPackage" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
CREATE INDEX IF NOT EXISTS "BanquetMenuPackage_organizationId_idx" ON "BanquetMenuPackage"("organizationId");
ALTER TABLE "BanquetEvent" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "BanquetEvent" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
CREATE INDEX IF NOT EXISTS "BanquetEvent_organizationId_idx" ON "BanquetEvent"("organizationId");
ALTER TABLE "RoomClosure" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "RoomClosure" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
CREATE INDEX IF NOT EXISTS "RoomClosure_organizationId_idx" ON "RoomClosure"("organizationId");
ALTER TABLE "LostFoundItem" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "LostFoundItem" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
CREATE INDEX IF NOT EXISTS "LostFoundItem_organizationId_idx" ON "LostFoundItem"("organizationId");
ALTER TABLE "satellite_audit_logs" ADD COLUMN IF NOT EXISTS "organizationId" TEXT NOT NULL DEFAULT 'unbound';
UPDATE "satellite_audit_logs" t SET "organizationId" = COALESCE((SELECT b."organizationId" FROM "_era_organization_bind" b WHERE b.id = 1 LIMIT 1), t."organizationId") WHERE t."organizationId" = 'unbound';
CREATE INDEX IF NOT EXISTS "satellite_audit_logs_organizationId_idx" ON "satellite_audit_logs"("organizationId");
