export const BankErrorCode = {
  EOD_LOCKED: "EOD_LOCKED",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  SOD_SELF_APPROVE: "SOD_SELF_APPROVE",
  LITE_NOT_DEEP: "LITE_NOT_DEEP",
  TARIFF_NOT_FOUND: "TARIFF_NOT_FOUND",
  TARIFF_INACTIVE: "TARIFF_INACTIVE",
  MOVEMENT_ALREADY_POSTED: "MOVEMENT_ALREADY_POSTED",
  CASE_NOT_FOUND: "CASE_NOT_FOUND",
  TRADE_INVALID_STATE: "TRADE_INVALID_STATE",
  STANDING_ORDER_NOT_DUE: "STANDING_ORDER_NOT_DUE",
  INVALID_STATE: "INVALID_STATE",
  UNKNOWN_TARIFF: "UNKNOWN_TARIFF",
  INSUFFICIENT_LIMIT: "INSUFFICIENT_LIMIT",
  RAIL_STUB_ONLY: "RAIL_STUB_ONLY",
  METHODOLOGY_LAB_ONLY: "METHODOLOGY_LAB_ONLY",
} as const;

export type BankErrorCode = (typeof BankErrorCode)[keyof typeof BankErrorCode];
