const EN: Record<string, string> = {
  field: 'Field',
  value: 'Value',
  date: 'Date',
  month: 'Month',
  time: 'Time',
  from: 'From',
  to: 'To',
  businessDate: 'Business date',
  dateFrom: 'From',
  dateTo: 'To',
  guestName: 'Guest',
  roomNumber: 'Room',
  department: 'Department',
  departmentCode: 'Department code',
  departmentName: 'Department',
  charge: 'Charge',
  payment: 'Payment',
  balance: 'Balance',
  description: 'Description',
  folioId: 'Folio',
  reservationId: 'Reservation',
  roomsAvailable: 'Rooms available',
  roomsSold: 'Rooms sold',
  occupancyPct: 'Occupancy %',
  revenue: 'Revenue',
  adr: 'ADR',
  revPar: 'RevPAR',
  arrivals: 'Arrivals',
  departures: 'Departures',
  inHouseGuests: 'In-house guests',
  total: 'Total',
  sourceCode: 'Source code',
  sourceName: 'Source',
  roomNights: 'Room nights',
  avgRate: 'Average rate',
  totalNights: 'Total nights',
  totalRevenue: 'Total revenue',
  totalCharges: 'Total charges',
  totalPayments: 'Total payments',
  segment: 'Segment',
  pctOfTotal: '% of total',
  roomTypeCode: 'Room type code',
  roomTypeName: 'Room type',
  quota: 'Quota',
  actualSold: 'Sold',
  actualOccPct: 'Occupancy %',
  variance: 'Variance',
  totalQuota: 'Total quota',
  totalSold: 'Total sold',
  totalRooms: 'Total rooms',
  sellableRooms: 'Sellable rooms',
  totalReservations: 'Reservations',
  cancellations: 'Cancellations',
  avgLos: 'Average LOS',
  guestNights: 'Guest nights',
  sold: 'Sold',
  stayovers: 'Stayovers',
  available: 'Available',
  currentSold: 'Sold (current)',
  currentOccPct: 'Occ % (current)',
  currentRevenue: 'Revenue (current)',
  priorSold: 'Sold (prior)',
  priorOccPct: 'Occ % (prior)',
  priorRevenue: 'Revenue (prior)',
  currentNights: 'Nights (current)',
  priorNights: 'Nights (prior)',
  changeNights: 'Nights change',
  agencyCode: 'Agency code',
  agencyName: 'Agency',
  commissionPct: 'Commission %',
  commissionAmount: 'Commission',
  totalCommission: 'Total commission',
  nationality: 'Nationality',
  dimension: 'Dimension',
  amount: 'Amount',
  count: 'Count',
  cube: 'Cube',
  market: 'Market',
  status: 'Status',
  roomType: 'Room type',
  revenueCode: 'Revenue code',
  agency: 'Agency',
  occupied: 'Occupied',
  vacant: 'Vacant',
  ooo: 'OOO',
  oos: 'OOS',
  complimentary: 'Complimentary',
  houseUse: 'House use',
};

const AZ: Record<string, string> = {
  field: 'Sahə',
  value: 'Dəyər',
  date: 'Tarix',
  month: 'Ay',
  time: 'Vaxt',
  from: 'Başlanğıc',
  to: 'Son',
  businessDate: 'İş günü',
  dateFrom: 'Başlanğıc',
  dateTo: 'Son',
  guestName: 'Qonaq',
  roomNumber: 'Otaq',
  department: 'Şöbə',
  departmentCode: 'Şöbə kodu',
  departmentName: 'Şöbə',
  charge: 'Yükləmə',
  payment: 'Ödəniş',
  balance: 'Balans',
  description: 'Təsvir',
  folioId: 'Folio',
  reservationId: 'Rezervasiya',
  roomsAvailable: 'Boş otaq',
  roomsSold: 'Satılmış otaq',
  occupancyPct: 'Doluluq %',
  revenue: 'Gəlir',
  adr: 'ADR',
  revPar: 'RevPAR',
  arrivals: 'Gəliş',
  departures: 'Gediş',
  inHouseGuests: 'Oteldeki qonaq',
  total: 'Cəmi',
  sourceCode: 'Mənbə kodu',
  sourceName: 'Mənbə',
  roomNights: 'Otaq gecəsi',
  avgRate: 'Orta tarif',
  totalNights: 'Cəmi gecə',
  totalRevenue: 'Cəmi gəlir',
  totalCharges: 'Cəmi yükləmə',
  totalPayments: 'Cəmi ödəniş',
  segment: 'Seqment',
  pctOfTotal: 'Cəmdən %',
  roomTypeCode: 'Otaq tipi kodu',
  roomTypeName: 'Otaq tipi',
  quota: 'Kvota',
  actualSold: 'Satılıb',
  actualOccPct: 'Doluluq %',
  variance: 'Fərq',
  totalQuota: 'Cəmi kvota',
  totalSold: 'Cəmi satılıb',
  totalRooms: 'Cəmi otaq',
  sellableRooms: 'Satıla bilən',
  totalReservations: 'Rezervasiya',
  cancellations: 'Ləğv',
  avgLos: 'Orta qalma',
  guestNights: 'Qonaq gecəsi',
  sold: 'Satılıb',
  stayovers: 'Qalan',
  available: 'Boş',
  currentSold: 'Satılıb (cari)',
  currentOccPct: 'Doluluq % (cari)',
  currentRevenue: 'Gəlir (cari)',
  priorSold: 'Satılıb (əvvəlki)',
  priorOccPct: 'Doluluq % (əvvəlki)',
  priorRevenue: 'Gəlir (əvvəlki)',
  currentNights: 'Gecə (cari)',
  priorNights: 'Gecə (əvvəlki)',
  changeNights: 'Gecə fərqi',
  agencyCode: 'Agent kodu',
  agencyName: 'Agent',
  commissionPct: 'Komissiya %',
  commissionAmount: 'Komissiya',
  totalCommission: 'Cəmi komissiya',
  nationality: 'Milliyyət',
  dimension: 'Ölçü',
  amount: 'Məbləğ',
  count: 'Say',
  cube: 'Kub',
  market: 'Bazar',
  status: 'Status',
  roomType: 'Otaq tipi',
  revenueCode: 'Gəlir kodu',
  agency: 'Agentlik',
  occupied: 'Dolu',
  vacant: 'Boş',
  ooo: 'OOO',
  oos: 'OOS',
  complimentary: 'Kompliment',
  houseUse: 'House use',
};

const RU: Record<string, string> = {
  field: 'Поле',
  value: 'Значение',
  date: 'Дата',
  month: 'Месяц',
  time: 'Время',
  from: 'С',
  to: 'По',
  businessDate: 'Операционный день',
  dateFrom: 'С',
  dateTo: 'По',
  guestName: 'Гость',
  roomNumber: 'Номер',
  department: 'Отдел',
  departmentCode: 'Код отдела',
  departmentName: 'Отдел',
  charge: 'Начисление',
  payment: 'Оплата',
  balance: 'Баланс',
  description: 'Описание',
  folioId: 'Фолио',
  reservationId: 'Бронь',
  roomsAvailable: 'Свободно номеров',
  roomsSold: 'Продано номеров',
  occupancyPct: 'Загрузка %',
  revenue: 'Выручка',
  adr: 'ADR',
  revPar: 'RevPAR',
  arrivals: 'Заезды',
  departures: 'Выезды',
  inHouseGuests: 'Гостей в отеле',
  total: 'Итого',
  sourceCode: 'Код источника',
  sourceName: 'Источник',
  roomNights: 'Номеро-ночи',
  avgRate: 'Средний тариф',
  totalNights: 'Всего ночей',
  totalRevenue: 'Выручка всего',
  totalCharges: 'Начисления всего',
  totalPayments: 'Оплаты всего',
  segment: 'Сегмент',
  pctOfTotal: '% от итога',
  roomTypeCode: 'Код типа',
  roomTypeName: 'Тип номера',
  quota: 'Квота',
  actualSold: 'Продано',
  actualOccPct: 'Загрузка %',
  variance: 'Отклонение',
  totalQuota: 'Квота всего',
  totalSold: 'Продано всего',
  totalRooms: 'Всего номеров',
  sellableRooms: 'К продаже',
  totalReservations: 'Брони',
  cancellations: 'Отмены',
  avgLos: 'Средняя длительность',
  guestNights: 'Госте-ночи',
  sold: 'Продано',
  stayovers: 'Проживающие',
  available: 'Свободно',
  currentSold: 'Продано (текущий)',
  currentOccPct: 'Загрузка % (текущий)',
  currentRevenue: 'Выручка (текущий)',
  priorSold: 'Продано (прошлый)',
  priorOccPct: 'Загрузка % (прошлый)',
  priorRevenue: 'Выручка (прошлый)',
  currentNights: 'Ночи (текущий)',
  priorNights: 'Ночи (прошлый)',
  changeNights: 'Изменение ночей',
  agencyCode: 'Код агентства',
  agencyName: 'Агентство',
  commissionPct: 'Комиссия %',
  commissionAmount: 'Комиссия',
  totalCommission: 'Комиссия всего',
  nationality: 'Гражданство',
  dimension: 'Измерение',
  amount: 'Сумма',
  count: 'Количество',
  cube: 'Куб',
  market: 'Рынок',
  status: 'Статус',
  roomType: 'Тип номера',
  revenueCode: 'Код дохода',
  agency: 'Агентство',
  occupied: 'Занято',
  vacant: 'Свободно',
  ooo: 'OOO',
  oos: 'OOS',
  complimentary: 'Комплимент',
  houseUse: 'House use',
};

const BY_LOCALE: Record<string, Record<string, string>> = { en: EN, az: AZ, ru: RU };

function humanize(key: string): string {
  const spaced = key.replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/_/g, ' ');
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}

export function columnLabel(locale: string, key: string): string {
  const bag = BY_LOCALE[locale] ?? EN;
  return bag[key] ?? EN[key] ?? humanize(key);
}
