import type { PrintLang } from "@/domain/print/print-types";

type Dict = Record<string, string>;

const EN: Dict = {
  parameter: "Parameter",
  result: "Result",
  norm: "Reference",
  unit: "Unit",
  no: "No",
  patient: "Patient",
  sex: "Sex",
  birthDate: "Date of birth",
  phone: "Phone",
  country: "Country",
  roomNo: "Room No",
  doctor: "Doctor",
  date: "Date",
  diagnosis: "Diagnosis",
  checkup: "Check-up",
  workingHours: "Working hours",
  weekdays: "Mon–Fri",
  saturday: "Sat",
  signature: "Signature",
  labDoctor: "Lab physician",
  radiologist: "Radiologist",
  doctorComment: "Doctor comment",
  temporarilyUnavailable: "Temporarily unavailable",
  procedureName: "Procedure",
  quantity: "Qty",
  time: "Time",
  room: "Room",
  price: "Price",
  note: "Notes",
  procedures: "Procedures",
  checkupList: "CHECK-UP LIST",
  height: "Height",
  weight: "Weight",
  arrival: "Arrival",
  departure: "Departure",
  address: "Address",
  print: "Print",
  chooseLanguage: "Print language",
  cancel: "Cancel",
  male: "Male",
  female: "Female",
  unknown: "—",
  bloodPressure: "Blood pressure",
  pulse: "Pulse",
  respiration: "Respiration",
  exam: "Examination",
  naftalanOpinion: "Opinion on Naftalan baths / physiotherapy",
  specialty_therapist: "Therapist",
  specialty_cardiologist: "Cardiologist",
  specialty_gynecologist: "Gynecologist",
  specialty_usm: "Ultrasound room",
  specialty_dermatoneurologist: "Dermatoneurologist",
  specialty_cosmetologist: "Cosmetologist",
  specialty_manual_therapist: "Manual therapist",
  extraTicket: "Extra procedure ticket",
  copyReception: "Copy 1 — reception",
  copyNurse: "Copy 2 — nurse",
  copyGuest: "Copy 3 — guest",
  ticketNo: "Ticket",
};

const RU: Dict = {
  ...EN,
  parameter: "Параметр",
  result: "Результат",
  norm: "Норма",
  unit: "Ед.",
  no: "№",
  patient: "Пациент",
  sex: "Пол",
  birthDate: "Дата рождения",
  phone: "Телефон",
  country: "Страна",
  roomNo: "№ палаты",
  doctor: "Врач",
  date: "Дата",
  diagnosis: "Диагноз",
  checkup: "Check-up",
  workingHours: "Часы работы",
  weekdays: "Пн–Пт",
  saturday: "Сб",
  signature: "Подпись",
  labDoctor: "Врач-лаборант",
  radiologist: "Врач-радиолог",
  doctorComment: "Комментарий врача",
  temporarilyUnavailable: "Временно нет",
  procedureName: "Процедура",
  quantity: "Кол-во",
  time: "Время",
  room: "Кабинет",
  price: "Цена",
  note: "Примечание",
  procedures: "Процедуры",
  checkupList: "CHECK-UP LIST",
  height: "Рост",
  weight: "Вес",
  arrival: "Прибытие",
  departure: "Выезд",
  address: "Адрес",
  print: "Печать",
  chooseLanguage: "Язык печати",
  cancel: "Отмена",
  male: "Мужской",
  female: "Женский",
  bloodPressure: "Артериальное давление",
  pulse: "Пульс",
  respiration: "Дыхание",
  exam: "Осмотр врача",
  naftalanOpinion: "Заключение по нафталановым ваннам / физиотерапии",
  specialty_therapist: "Терапевт",
  specialty_cardiologist: "Кардиолог",
  specialty_gynecologist: "Гинеколог",
  specialty_usm: "Кабинет УЗИ",
  specialty_dermatoneurologist: "Дерматоневролог",
  specialty_cosmetologist: "Косметолог",
  specialty_manual_therapist: "Мануальный терапевт",
  extraTicket: "Чек дополнительной процедуры",
  copyReception: "Копия 1 — ресепшен",
  copyNurse: "Копия 2 — медсестра",
  copyGuest: "Копия 3 — гость",
  ticketNo: "Чек",
};

const AZ: Dict = {
  ...EN,
  parameter: "Parametr",
  result: "Nəticə",
  norm: "Norma",
  unit: "Vahid",
  no: "№",
  patient: "Pasiyent",
  sex: "Cins",
  birthDate: "Təvəllüd",
  phone: "Telefon",
  country: "Ölkə",
  roomNo: "Palata №",
  doctor: "Həkim",
  date: "Tarix",
  diagnosis: "Diaqnoz",
  checkup: "Check-up",
  workingHours: "İş saatları",
  weekdays: "I–V",
  saturday: "VI",
  signature: "İmza",
  labDoctor: "Həkim laborant",
  radiologist: "Dr.Radioloq",
  doctorComment: "Həkim şərhi",
  temporarilyUnavailable: "Müvəqqəti yoxdur",
  procedureName: "Prosedur adı",
  quantity: "Say",
  time: "Saat",
  room: "Otaq",
  price: "Qiymət",
  note: "Qeyd",
  procedures: "Prosedurlar",
  checkupList: "CHECK-UP LIST",
  height: "Boy",
  weight: "Çəki",
  arrival: "Gəliş tarixi",
  departure: "Gediş tarixi",
  address: "Ünvan",
  print: "Çap",
  chooseLanguage: "Çap dili",
  cancel: "Ləğv",
  male: "Kişi",
  female: "Qadın",
  bloodPressure: "Arterial təzyiq",
  pulse: "Puls",
  respiration: "Tənəffüs",
  exam: "Həkim baxışı",
  naftalanOpinion: "Naftalan vanna və ya fizioterapiya üzrə rəy",
  specialty_therapist: "Həkim terapevt",
  specialty_cardiologist: "Kardioloq",
  specialty_gynecologist: "Ginekoloq",
  specialty_usm: "USM Kabineti",
  specialty_dermatoneurologist: "Dermatonevroloq",
  specialty_cosmetologist: "Kosmetoloq",
  specialty_manual_therapist: "Manual terapevt",
  extraTicket: "Əlavə prosedur çeki",
  copyReception: "Nüsxə 1 — resepsiya",
  copyNurse: "Nüsxə 2 — tibb bacısı",
  copyGuest: "Nüsxə 3 — qonaq",
  ticketNo: "Çek",
};

const BY_LANG: Record<PrintLang, Dict> = { en: EN, ru: RU, az: AZ };

export function printLabel(lang: PrintLang, key: string): string {
  return BY_LANG[lang][key] ?? EN[key] ?? key;
}
